module.exports = {
    API: {
        // 用户
        user_login: '/user/login',
        user_regsave: '/user/regsave',
        user_getmybank: '/user/getmybank',
        user_getbalance: '/user/getbalance',
        user_getverifycode: '/user/getverifycode',
        user_checkverifycode: '/user/checkverifycode',
        user_weixinBind: '/user/weixinBind',
        user_wxlogin: '/user/wxlogin',
        user_modifypwd: '/user/modifypwd',
        user_modifypwd2: '/user/modifypwd2',
        user_modifyrealname: '/user/modifyrealname',
        user_modifytel: '/user/modifytel',
        user_iolist: '/user/iolist',
        user_getdelta: '/user/getdelta',
        user_getdraw: '/user/getdraw',
        user_getcity: '/user/getcity',
        user_savebank: '/user/savebank',
        user_removebank: '/user/removebank',
        user_getbank: '/user/getbank',
        user_getCouponModel: '/user/getCouponModel',
        user_exchange: '/user/exchange',
        user_uploadHeader: '/user/uploadHeader',
        user_upload: '/upload',
        user_getverify: '/user/getverify',
        user_savemsg: '/user/savemsg',
        user_getaccountrpt: '/user/getaccountrpt',
        user_gettrackinfo: '/user/gettrackinfo',
        user_gethistrasbill: '/user/gethistrasbill',
        user_getmytrack: '/user/getmytrack',
        user_sharemsg: '/user/sharemsg',
        user_getappverifycode: '/user/getappverifycode',
        user_getnotice: '/user/getnotice',
        user_setnotice: '/user/setnotice',
        user_favors: '/user/favors',
        user_subscribe: '/user/subscribe',
        user_cancel: '/user/cancel',
        user_status: '/user/status',
        user_shareContract: '/user/shareContract',
        user_outlets: "/user/bank/outlets",
        user_checkSMSCode: "/user/checkverifycode",
        user_newsList: "/news/list",
        user_noticeList: "/news/board/notice",
        user_promotionList: "/news/board/promotion",
        user_systemList: "/news/board/system",
        user_initData: "/news/initData",
        // 操盘
        trade_draw: '/trade/draw',
        trade_getProduct: '/trade/getProduct',
        trade_get: '/trade/get',
        trade_deal: '/trade/deal',
        trade_tradelist: '/trade/tradelist',
        trade_gettradeinfo: '/trade/gettradeinfo',
        trade_quittrans: '/trade/quittrans',
        trade_addfxamount: '/trade/addfxamount',
        trade_getinterest: '/trade/getinterest',
        trade_getstocklimit: '/trade/getstocklimit',
        trade_fetchprofit: '/trade/fetchprofit',
        trade_wxpay: '/trade/wxpay',
        trade_assetsorder: '/trade/assetsorder',
        trade_sendpaycode: '/trade/sendpaycode',
        trade_getpaycode: '/trade/getpaycode',
        trade_getPromotions: '/trade/getPromotions',
        trade_getPromotionDetail: '/trade/getPromotionDetail',
        trade_payQuota: '/trade/payQuota',
        trade_applyPromotionTrade: '/trade/applyPromotionTrade',
        trade_tradeFlowDetail: '/trade/io/list',
        trade_multiple: '/trade/suspendedStock/multiple',
        trade_cacl: '/trade/suspendedStock/calc',
        trade_order: '/trade/suspendedStock/order',
        trade_extension: '/trade/paidRenewTrans',
        trade_coupon: '/coupon/trade',
        trade_couponList: '/coupon/member',
        trade_canceldraw: "/trade/canceldraw",
        // 交易买卖
        tradeclient_getAccountCode: '/tradeclient/getAccountCode',
        tradeclient_queryNoneExecution: '/tradeclient/queryNoneExecution',
        tradeclient_queryPosition: '/tradeclient/queryPosition',
        tradeclient_queryEntrust: '/tradeclient/queryEntrust',
        tradeclient_queryExecution: '/tradeclient/queryExecution',
        tradeclient_queryHistoryEntrust: '/tradeclient/queryHistoryEntrust',
        tradeclient_queryHistoryExecution: '/tradeclient/queryHistoryExecution',
        tradeclient_cancelOrder: '/tradeclient/cancelOrder',
        tradeclient_queryAccount: '/tradeclient/queryAccount',
        tradeclient_queryStock: '/tradeclient/queryStock',
        tradeclient_queryStockPrice: '/tradeclient/queryStockPrice',
        tradeclient_sendOrder: '/tradeclient/sendOrder',
        tradeclient_queryCapFlw: '/tradeclient/queryCapFlw',
        tradeclient_queryHisCapFlw: '/tradeclient/queryHisCapFlw',
        tradeclient_queryQty: '/tradeclient/queryQty',

        // 推广
        extension_info: '/extension/info',
        extension_users: '/extension/users',
        extension_incomes: '/extension/incomes',
        extension_redbag: '/extension/redbag',
        extension_rule: '/extension/rule',

        // 居间商
        agent_reg: '/agent/reg',
        agent_plogin: '/agent/plogin',
        agent_modifyPwd: '/agent/modifyPwd',
        agent_getverifycode: '/agent/getverifycode',
        agent_getmypartner: '/agent/getmypartner',
        agent_getmybank: '/agent/getmybank',
        agent_getdraw: '/agent/getdraw',
        agent_getdrawcode: '/agent/getdrawcode',
        agent_getmybank: '/agent/getmybank',
        agent_getbank: '/agent/getbank',
        agent_savebank: '/agent/savebank',
        agent_removebank: '/agent/removebank',
        agent_domain: '/agent/modifyDomain',
        agent_getRegList: '/agent/getRegList',
        agent_getTradeList: '/agent/getTradeList',
        agent_getdetial: '/agent/detail/',

        // 充值
        pay_quickmodel: '/pay/quickmodel',
        pay_applyorder: '/pay/applyorder',
        pay_transfer: '/pay/transfer',

        // 点买
        buy_buyStock: '/buy/stock',
        buy_ruler: '/buy/rule',
        buy_estimated: '/buy/get',
        buy_buyOrder: '/buy/order',
        buy_buyList: '/buy/orders',
        buy_returnAmount: '/buy/returnAmount',
        buy_repayFlow: '/buy/returnAmount/order',

        // 其他
        product_advert: '/product/advert',
        match_joinNovice: '/match/join-novice',
        novice_experience: '/novice/experience',
        news_list: '/news/list',
        news_read: '/news/read',
        appversion: '/app/version',
        report: '/report',

        //cms
        cms_findByAdspaceId: '/cmsmanager/cms/advertising/findByAdspaceId',
        cms_findByChannelId: '/cmsmanager/cms/content/findByChannelId',
        cms_findByTagId: '/cmsmanager/cms/content/findByTagId',
        // 活动
        promote_action: '/promote/action',
        promote_signIn: '/promote/signIn',
        promote_tradeCash: '/promote/tradeCash',
        promote_invite: '/promote/invite',
        // 体验活动
        match_getstep: '/match/getmatchstep',
        match_join_weekmatch: '/match/join-weekMatch',
        // 世界杯
        wxpromote_list: '/wxpromote/list',
        wxpromote_one: '/wxpromote',
        wxpromote_get_record: '/wxpromote/get',
        wxpromote_action_create: '/wxpromote/action',
        wxpromote_action_join: '/wxpromote/action'
    },
    ERROR: {
        key: '请输入正确的手机号',
        telephone: '请输入正确的手机号',
        mobilephone: '请输入正确的手机号',
        phone: '请输入正确的手机号',
        username: '请输入用户名或手机号',
        password: '请输入密码',
        verifyCode: '请输入短信验证码',
        ivc: '请输入图片验证码',
        realName: '请输入姓名',
        cardBank: '请选择开户银行',
        bankName: '请选择开户银行',
        proName: '请选择开户行所在省市',
        cityName: '请选择开户行所在城市',
        outletsName: '请填写开户行信息',
        bankId: '请选择银行卡',
        cardNo: '请填写12位或16至22位的银行卡号',
        cardNo2: '两次卡号输入不一致',
        differentCardNo: '两次卡号输入不一致',
        phoneNumber: '请输入预留的手机号码',
        // idCard:'请输入16或19位银行卡号',
        idCard: '请输入正确的身份证号',
        idcard: '请先实名认证',
        oldPwd: '密码由6-16位数字和字母组成',
        pwd: '密码由6-16位数字和字母组成',
        pwd2: '两次密码输入不一致',
        deltaAmount: '请输入正确的充值金额',
        emptyDefault: '输入不能为空',
        login: '用户名或密码错误',
        serverDefault: '系统异常，请稍后再试',
        profitAmount: '请输入正确的提取资金',
        nobalance: '余额不足，请前往充值',
        fxAmount: '请输入正确的保证金',
        minFxAmount: '保证金不能小于最低追加金额',
        mutiple: '请选择投入资金',
        stockCode: '请输入正确的股票代码',
        images: '上传图片失败',
        bigImages: '请上传不大于2M的*.jpg;*.png;*.jpeg;*.gif图片',
        price: '请输入正确的股票价格',
        qty: '请输入正确的股票数量',
        drawAmount: '请输入正确的提款金额',
        drawPwd: '请输入提款密码',
        drawBankCard: '请选择银行卡',
        support: '您的银行卡暂不支持本通道充值，请使用其他充值方式！',
        msgType: '请选择投诉类型',
        content: '问题描述在10到500个字之间!',
        contentNum: '问题描述在10到500个字之间!',
        partnerName: '请输入正确的用户名',
        corporationName: '公司名称不能为空',
        corporationCode: '公司组织机构代码不能为空',
        companyContacts: '联系人姓名不能为空',
        address: '公司详细地址不能为空',
        picFile: '请选择正确的营业执照',
        remark: '渠道资源介绍不能为空',
        remarkRecharge: '请选择备注信息',
        corporationCode1: '职业证书编号不能为空',
        pzAmount: '请输入符合交易范围的金额',
        deltaMoney: '充值金额不能小于100元',
        canCreateFront: "可配额度不足，请尝试申请其它类型合约",
        arrearsCost: "您的合约处于欠费状态，无法申请停牌转合约！",
        offlineRemark: '请添加充值备注',
        offlineImage: '请上传充值凭证',
        tempAttachment: '请上传充值凭证',
        amount: '请输入金额',
        repayment: '请输入符合还款范围的金额',
        addCapital: '请追加符合范围的本金',
        extension: '该合约已超出最长可延期范围',
        couponCode: '优惠券码不能为空',
        openId: 'openId获取失败，请重新授权'
    },
    SUCCESS: {
        recharge: '充值成功',
        profit: '提取成功',
        extension: '延期成功',
        draw: '恭喜您，提款成功!',
        saveBank: '添加银行成功!',
        trade: '您的配资已经申请成功，请立即前往交易',
        coupon: '添加优惠券成功！',
        ForgetPwd: '修改密码成功！',
        addCapital: '追加保证金成功！'
    },
    TABS: {
        // 头部
        HEADER: [{
            tabName: /(\/trade\/(\d+))|(\/tradeclient)|(\/trade\/list)|(\/trade\/hislist)|(\/trade\/detail)|(\/trade\/hisdetail)|(\/tradevip\/(\d+))/,
            index: 1,
            tabDom: 'JS-tab'
        }, {
            tabName: '/activity/experience',
            index: 2,
            tabDom: 'JS-tab'
        }, {
            tabName: '/activity',
            index: 3,
            tabDom: 'JS-tab'
        }, {
            tabName: '/activity/noviceGuide',
            index: 4,
            tabDom: 'JS-tab'
        }, {
            tabName: '/',
            index: 0,
            tabDom: 'JS-tab'
        }],
        TRADE_HEADER: [{
            tabName: /\/trade\/(\d+)/,
            index: 0,
            tabDom: 'JS-tab-trade'
        }, {
            tabName: /\/trade\/flashsale/,
            index: 1,
            tabDom: 'JS-tab-trade'
        }, {
            tabName: /(\/trade\/list)|(\/tradeclient)|(\/trade\/hislist)|(\/trade\/detail)|(\/trade\/hisdetail)/,
            index: 2,
            tabDom: 'JS-tab-trade'
        }],
        TRADE_PRODUCT_HEADER: [{
            tabName: '/trade/0',
            index: 0,
            tabDom: 'JS-product-tab'
        }, {
            tabName: '/trade/15',
            index: 15,
            tabDom: 'JS-product-tab'
        }, {
            tabName: '/trade/1',
            index: 1,
            tabDom: 'JS-product-tab'
        }, {
            tabName: '/trade/9',
            index: 9,
            tabDom: 'JS-product-tab'
        }, {
            tabName: '/trade/5',
            index: 5,
            tabDom: 'JS-product-tab'
        }, {
            tabName: '/trade/900005',
            index: 900005,
            tabDom: 'JS-product-tab'
        }, {
            tabName: '/trade/6',
            index: 6,
            tabDom: 'JS-product-tab'
        }, {
            tabName: '/trade/12',
            index: 12,
            tabDom: 'JS-product-tab'
        }],
        TRADE_FREEP_HEADER: [{
            tabName: '/trade/5',
            index: 5,
            tabDom: 'JS-freeProduct'
        }, {
            tabName: '/trade/9',
            index: 9,
            tabDom: 'JS-freeProduct'
        }],
        OTHER_LEFT_HEADER: [{
            tabName: '/other/aboutus',
            index: 0,
            tabDom: 'JS-tab-other'
        }, {
            tabName: '/other/contactus',
            index: 1,
            tabDom: 'JS-tab-other'
        }, {
            tabName: '/other/joinus',
            index: 2,
            tabDom: 'JS-tab-other'
        }, {
            tabName: '/other/safe',
            index: 3,
            tabDom: 'JS-tab-other'
        }, {
            tabName: /\/other\/(media)|(mediaDetail)/,
            index: 4,
            tabDom: 'JS-tab-other'
        }],
        USER_CENTER_HEADER: [{
            tabName: '/user/assets',
            index: 0,
            tabDom: 'JS-tab-user'
        }, {
            tabName: '/trade/list',
            index: 1,
            tabDom: 'JS-tab-user'
        }, {
            tabName: '/user/extend',
            index: 2,
            tabDom: 'JS-tab-user'
        }, {
            tabName: '/user/coupon',
            index: 3,
            tabDom: 'JS-tab-user'
        }, {
            tabName: '/user/flowing',
            index: 4,
            tabDom: 'JS-tab-user'
        }, {
            tabName: '/user/message',
            index: 5,
            tabDom: 'JS-tab-user'
        }]
    },
    PageSize: 10,
    CountDown: 60,
    SmsBtnText: '发送短信验证码',
    SendCode_ForgetPwd: 1,
    SendCode_ForgetTradePwd: 3,
    SendCode_Register: 0,
    SendCode_checkSMSCode: 2,
    SendCode_modifyTel: 2,
    cycleTradeDay: '交易日',
    cycleTradeMonth: '月',
    cycleTradeWeek: '周',
    tradeFormulaDay: '准备资金 = 投资本金 + 日管理费 x 天数',
    tradeFormulaMonth: '准备资金 = 投资本金 + 月管理费 x 月数',
    mgAgtCouponTypeCode: '310001',
    cashCouponTypeCode: '310002',
    mediaTypeCode: '800002'
};